# "whoami" crate - Licensed under the MIT LICENSE
#  * Copyright (c) 2017-2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "whoami"
version = "0.2.1"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>",
	"Mark Swaanenburg <cygnus9@users.noreply.github.com>"
]

license = "MIT"
documentation = "https://docs.rs/whoami"
homepage = "http://plopgrizzly.com/whoami"
repository = "https://github.com/plopgrizzly/whoami"

readme = "readme.md"
description = "Retrieve the current user and environment."
keywords = ["user", "username", "whoami", "platform", "detect"]
categories = ["os"]

exclude = ["examples/*", "code_of_conduct.md", "contributing.md", ".gitignore"]

[dependencies]
libc = "0.2"
term = { version = "0.5", optional = true }

[[bin]]
name = "whoami"
doc = false
